### ISSUE TITLE
Shift doesn't work

### ISSUE THREAD

**Issue by adv0r** [ExodusMovement/shapeshift.io#2]
Is this library outdated ? 

I am using the dist js file and cannot shift.  

the post method is actually calling a get : 

```
function post (url, data, callback) {
  xhr({ method: 'GET', url: url, json: true, timeout: 30000, data: data }, function (err, resp, body) {
```

I changed to method:'POST' and now got a json error `Invalid or poorly formed JSON` .

**Comment by jprichardson** [comment]
> Is this library outdated ?

No, I use it daily in http://www.exodus.io/

> the post method is actually calling a get :

Ah, ok. I don't use the browser http transport personally. That may be way. Are you using npm by chance?

**Comment by adv0r** [comment]
> Are you using npm by chance?

Nope, I am using the file you compiled with browserify I guess.

**Comment by jprichardson** [comment]
Thanks for the catch on 'GET' vs 'POST'... change (https://github.com/ExodusMovement/shapeshift.io/blob/47147a5c4c77393085b5e3bc49b264bf41d55b88/dist/shapeshift.js#L13)

```js
xhr({ method: 'GET', url: url, json: true, timeout: 30000, data: data }, function (err, resp, body) {
```

to

```js
xhr({ method: 'POST', url: url, json: true, timeout: 30000, body: JSON.stringify(data) }, function (err, resp, body) {
```

Note the changes: `'POST'`, `data` => `body` and `JSON.stringify`.

Let me know if that works.

**Comment by jprichardson** [comment]
Did this work for you?

**Comment by adv0r** [comment]
Thanks, I gave up and decided to write my own library, I only needed one
method so it didn't make sense to load an entire library.
Thanks

On Sat, Mar 19, 2016 at 10:32 AM, JP Richardson <notifications@github.com>
wrote:

> Did this work for you?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ExodusMovement/shapeshift.io/issues/2#issuecomment-198673990>
>



-- 
❝  Nicolò Paternoster
☎  +34 603.678.719
ଭ  adva.io

**Comment by fanatid** [comment]
@jprichardson I think that right request should be:
```js
xhr({ method: 'POST', url: url, json: data, timeout: 30000 }, function (err, resp, body) {
```
because https://github.com/Raynos/xhr/blob/341450ea3cf21405df2349ea2d0df309d896e9d3/index.js#L162

and `GET`:
```js
xhr({ method: 'GET', url: url, json: undefined, timeout: 30000 }, function (err, resp, body) {
```
